"""init database migration

Revision ID: c1f1b1b57ccb
Revises: 
Create Date: 2024-10-03 16:46:59.666426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f1b1b57ccb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('notification_level', sa.Enum('PRESENT_ONLY', 'ABSENT_ONLY', 'ALL', name='notificationlevel'), nullable=False),
    sa.CheckConstraint("email ~ '^[^@]+@[^@]+\\.[^@]+$'", name='check_email_format'),
    sa.CheckConstraint('length(username) == 6', name='check_username_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attendance',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('max_hours', sa.Integer(), nullable=False),
    sa.Column('attended_hours', sa.Integer(), nullable=False),
    sa.Column('absent_hours', sa.Integer(), nullable=False),
    sa.Column('total_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subject_code', name='attendance_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('users')
    # ### end Alembic commands ###
